# DEV Server Port
server.port=7303

logging.level.com.ibk=info
logging.level.org.springframework=info

# feign logs
feign.client.config.box-kipris-api.logger-level = basic

feign.client.config.box-open-api-account.logger-level = basic
feign.client.config.box-open-api-cm-alarm.logger-level = basic
feign.client.config.box-open-api-doc.logger-level = basic

feign.client.config.box-open-api-mnb-ivt-key.logger-level = basic
feign.client.config.box-open-api-stamp.logger-level = basic

feign.client.config.box-open-api-login.logger-level = basic
feign.client.config.box-open-api-com.logger-level = basic
feign.client.config.box-open-api-file.logger-level = basic

#feing platform url
feign.box-open-api.url = https://api.ibkplatform.net:8443
feign.box-kipris-api.url = https://api.ibkplatform.net:8443/api/kipris/v1

#feing platform key
feign.mnb-api.key = l7xx7y7VsSbny3BXsCfitO5SNKFuKVgeWe0i
feign.ivt-api.key = l7xxKxHShodZ3jgS0VkI7lcfyTk0wpuwOUTG
feign.mkt-api.key = l7xx0ldfHhb8OgaIjW6Nwb9rANy289g0ojSn
feign.kipris-api.key =CUHjoHjVjHbMyx=s0onA59yrSyleZO9LZLs3bHuwjsg=

feign.ibk-api.key = l7xxiyUIa4S0wvK06Q8qhICZf9XKkDzOHfO9
feign.ibk-api.secret = ENC(+6bgHl2vY9ZISrPjyw295FOydfJr10NhSBl0u5omZgR+X9X0Gr3YDbUGRcTtC3bb)

# ibk jasypt password
#jasypt.encryptor.bean = jasyptStringEncryptor
jasypt.encryptor.password = box-api-world
jasypt.encryptor.algorithm = PBEWithMD5AndDES

# ibk dispatch email
com.ibk.email.dispatch.address = webmaster@rts.ibk.co.kr

#jwt
jwt.secretKey=ibkboxcomboxpijwtsecretKey
#5\u00EB\u00B6\u0084
jwt.validity=300000

# JNDI\u00EB\u00A1\u009C WAS DataSource \u00EC\u0084\u00B8\u00ED\u008C\u0085
spring.datasource.jndi-name=PLRB02DB

# Upload Path
com.ibk.api.upload.img.path=/box_data/ivb/images/
com.ibk.api.upload.doc.path=/box_data/ivb/doc/
com.ibk.api.upload.nda.path=/box_data/ivb/nda/
# com.ibk.api.upload.tmp.path=/box_data/ivb/tmp/

# Content Path
com.ibk.content.img.path.ivt-v1=https://invest.ibkbox.net/api/iv/v1/file/render/image/
com.ibk.content.img.path.mnb-v1=https://www.ibkbox.net/renderImg.do?fileMngmNo=

# IBK \u00ED\u0088\u00AC\u00EC\u009E\u0090\u00EC\u0082\u00AC \u00EC\u0082\u00AC\u00EC\u0097\u0085\u00EC\u009E\u0090\u00EB\u00B2\u0088\u00ED\u0098\u00B8 (\u00EC\u00A4\u0091\u00EC\u0086\u008C\u00EA\u00B8\u00B0\u00EC\u0097\u0085\u00EC\u009D\u0080\u00ED\u0096\u0089)
# \u00EC\u0097\u00AC\u00EB\u009F\u00AC\u00EA\u00B0\u009C\u00EC\u009D\u00BC \u00EA\u00B2\u00BD\u00EC\u009A\u00B0 \u00EA\u00B5\u00AC\u00EB\u00B6\u0084\u00EC\u009E\u0090\u00EB\u00A1\u009C , \u00EC\u0082\u00AC\u00EC\u009A\u00A9
ivt.ibk.vc.biznum = 2028100978

# \u00ED\u0088\u00AC\u00EC\u009E\u0090\u00EB\u00B0\u0095\u00EC\u008A\u00A4 \u00ED\u0094\u0084\u00EB\u00A1\u00A0\u00ED\u008A\u00B8 \u00EB\u008F\u0084\u00EB\u00A9\u0094\u00EC\u009D\u00B8 \u00EA\u00B2\u00BD\u00EB\u00A1\u009C (\u00EC\u0095\u008C\u00EB\u00A6\u00BC URL)
ivt.alarm.page.host.url = https://invest.ibkbox.net

# \u00EC\u0095\u008C\u00EB\u00A6\u00BC \u00EC\u00A4\u0091\u00EB\u00B6\u0084\u00EB\u00A5\u0098 (\u00ED\u0088\u00AC\u00EC\u009E\u0090\u00EB\u00B0\u0095\u00EC\u008A\u00A4)
adp.alarm.mddv.ivt.code = APP00046

# Alarm ID (\u00EC\u009A\u00B4\u00EC\u0098\u0081\u00EC\u009E\u0090\u00ED\u008F\u00AC\u00ED\u0083\u0088 \u00EC\u0095\u008C\u00EB\u00A6\u00BC\u00EC\u0084\u00A4\u00EC\u00A0\u0095)
adp.alarm.audit-suggest.id = A00076
adp.alarm.audit-request.id = A00077
adp.alarm.audit-change-step.id = A00078
adp.alarm.audit-over-time.id = A00079
adp.alarm.audit-message-receive.id = A00080
adp.alarm.consult-answer.id = A00081
adp.alarm.biz-inquiry.id = A00082
adp.alarm.biz-inquiry-answer.id = A00083
adp.alarm.qna-answer.id = A00084
adp.alarm.nda-request.id = A00085
adp.alarm.nda-change-step.id = A00086
adp.alarm.convert-investor.id= A00087
adp.alarm.convert-company.id= A00088

# Terms Number
adp.terms.personal-info.id = 10027
adp.terms.box-service.id = 10151

adp.terms.auto-scp-collect.id = 10146
adp.terms.auto-scp-trade-view.id = 10147
adp.terms.auto-scp-collect-choice.id = 10148

# Open Date (YYYYMMDD)
ivt.open.date = 20240405

# prod profile swagger-ui turn off
springfox.documentation.enabled=false

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false