# DEV Server Port!
server.port=7301

# log
#logging.level.com.ibk=debug
logging.level.org.springframework=debug

# feign log
feign.client.config.box-kipris-api.logger-level = full

feign.client.config.box-open-api-account.logger-level = full
feign.client.config.box-open-api-cm-alarm.logger-level = full
feign.client.config.box-open-api-doc.logger-level = full

feign.client.config.box-open-api-login.logger-level = full
feign.client.config.box-open-api-com.logger-level = full
feign.client.config.box-open-api-file.logger-level = full

feign.client.config.box-open-api-mnb-ivt-key.logger-level = full
feign.client.config.box-open-api-stamp.logger-level = full

#feing platform url
#feign.box-mnb-site.url = https://devwww.ibkbox.net
feign.box-open-api.url = https://devapi.ibkplatform.net:8443
feign.box-kipris-api.url = https://devapi.ibkplatform.net:8443/api/kipris/v1

#feing platform key
feign.mnb-api.key = l7xxVAFzoS1ucg8TTeZkfv8ryFRgo5VZvNg5
feign.mkt-api.key = l7xxydcl4orvPHlbbDEhZAc7r2w9S5m5kxUY
feign.ivt-api.key = l7xxpWhaQSKILmrE9RQ2C3BK3E65151EzPxm
feign.kipris-api.key =CUHjoHjVjHbMyx=s0onA59yrSyleZO9LZLs3bHuwjsg=

feign.ibk-api.key = l7xxKoR7FoY4K358NtEzA9LRMvO3A1I69ViW
feign.ibk-api.secret = ENC(misKEu5Y2rcOgsLB08V8WMnFUxLfV+tLoVyJnSl7OnKP5AvGNvKt8U6ZHAtMzUU5)

# ibk jasypt password
#jasypt.encryptor.bean = jasyptStringEncryptor
jasypt.encryptor.password = box-api-world
jasypt.encryptor.algorithm = PBEWithMD5AndDES

#jwt
jwt.secretKey=ibkboxcomboxpijwtsecretKey
#5\ubd84
jwt.validity=300000

# DB Connection
spring.datasource.hikari.driver-class-name=com.tmax.tibero.jdbc.TbDriver
spring.datasource.hikari.jdbc-url=jdbc:tibero:thin:@10.29.12.91:18629:DLRB01DB
spring.datasource.hikari.username=A00222
spring.datasource.hikari.password=jinsol1!

# Upload Path
com.ibk.api.upload.img.path=C:/ibk-box-dev/ibkbox_invest_box_i/upload/box_data/ivt/images/
#com.ibk.api.upload.doc.path=C:/ibk-box-dev/ibkbox_invest_box_i/upload/box_data/ivt/doc/
com.ibk.api.upload.doc.path=Z:/ibk-box-dev/ibkbox_invest_box_i/upload/box_data/ivt/doc/
com.ibk.api.upload.nda.path=C:/ibk-box-dev/ibkbox_invest_box_i/upload/box_data/ivt/nda/
# com.ibk.api.upload.tmp.path=C:/ibk-box-dev/ibkbox_invest_box_i/upload/box_data/ivt/tmp/

# Content Path
com.ibk.content.img.path.ivt-v1=https://localhost:7301/api/iv/v1/file/render/image/
com.ibk.content.img.path.mnb-v1=https://devwww.ibkbox.net/renderImg.do?fileMngmNo=

server.ssl.key-store=keystore.p12
server.ssl.key-store-password=qwer123!
server.ssl.keyStoreType=PKCS12
server.ssl.key-alias=tomcat

# IBK \ud22c\uc790\uc0ac \uc0ac\uc5c5\uc790\ubc88\ud638 (\uc911\uc18c\uae30\uc5c5\uc740\ud589 usisId C0000714, biznum 2028100978)
# \uc5ec\ub7ec\uac1c\uc77c \uacbd\uc6b0 \uad6c\ubd84\uc790\ub85c , \uc0ac\uc6a9
ivt.ibk.vc.biznum = 2028100978

# \ud22c\uc790\ubc15\uc2a4 \ud504\ub860\ud2b8 \ub3c4\uba54\uc778 \uacbd\ub85c (\uc54c\ub9bc URL)
ivt.alarm.page.host.url = https://devinvest.ibkbox.net

# \uc54c\ub9bc \uc911\ubd84\ub958 (\ud22c\uc790\ubc15\uc2a4)
adp.alarm.mddv.ivt.code = APP00046

# Alarm ID (\uc6b4\uc601\uc790\ud3ec\ud0c8 \uc54c\ub9bc\uc124\uc815)
adp.alarm.audit-suggest.id = A00080
adp.alarm.audit-request.id = A00081
adp.alarm.audit-change-step.id = A00082
adp.alarm.audit-over-time.id = A00083
adp.alarm.audit-message-receive.id = A00084
adp.alarm.consult-answer.id = A00085
adp.alarm.biz-inquiry.id = A00086
adp.alarm.biz-inquiry-answer.id = A00087
adp.alarm.qna-answer.id = A00088
adp.alarm.nda-request.id = A00089
adp.alarm.nda-change-step.id = A00090
adp.alarm.convert-investor.id = A00106
adp.alarm.convert-company.id = A00107

# Terms Number
adp.terms.personal-info.id = 10027
adp.terms.box-service.id = 10151

adp.terms.auto-scp-collect.id = 10146
adp.terms.auto-scp-trade-view.id = 10147
adp.terms.auto-scp-collect-choice.id = 10148

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false