# DEV Server Port
server.port=7302

logging.level.com.ibk=debug
logging.level.org.springframework=debug

# feign log
feign.client.config.box-kipris-api.logger-level = basic

feign.client.config.box-open-api-account.logger-level = basic
feign.client.config.box-open-api-cm-alarm.logger-level = basic
feign.client.config.box-open-api-doc.logger-level = basic

feign.client.config.box-open-api-login.logger-level = basic
feign.client.config.box-open-api-com.logger-level = basic
feign.client.config.box-open-api-file.logger-level = basic

feign.client.config.box-open-api-mnb-ivt-key.logger-level = basic
feign.client.config.box-open-api-stamp.logger-level = basic

#feing platform url
feign.box-open-api.url = https://devapi.ibkplatform.net:8443
feign.box-kipris-api.url = https://devapi.ibkplatform.net:8443/api/kipris/v1

#feing platform key
feign.mnb-api.key = l7xxVAFzoS1ucg8TTeZkfv8ryFRgo5VZvNg5
feign.ivt-api.key = l7xxpWhaQSKILmrE9RQ2C3BK3E65151EzPxm
feign.mkt-api.key = l7xxydcl4orvPHlbbDEhZAc7r2w9S5m5kxUY
feign.kipris-api.key =CUHjoHjVjHbMyx=s0onA59yrSyleZO9LZLs3bHuwjsg=

feign.ibk-api.key = l7xxKoR7FoY4K358NtEzA9LRMvO3A1I69ViW
feign.ibk-api.secret = ENC(misKEu5Y2rcOgsLB08V8WMnFUxLfV+tLoVyJnSl7OnKP5AvGNvKt8U6ZHAtMzUU5)

# ibk jasypt password
#jasypt.encryptor.bean = jasyptStringEncryptor
jasypt.encryptor.password = box-api-world
jasypt.encryptor.algorithm = PBEWithMD5AndDES

# ibk dispatch email
com.ibk.email.dispatch.address = webmaster@rts.ibk.co.kr

#jwt
jwt.secretKey=ibkboxcomboxpijwtsecretKey
#5\uBD84
jwt.validity=300000

# JNDI\uB85C WAS DataSource \uC138\uD305
spring.datasource.jndi-name=DLRB02DB

# Upload Path
com.ibk.api.upload.img.path=/box_data/ivb/images/
com.ibk.api.upload.doc.path=/box_data/ivb/doc/
com.ibk.api.upload.nda.path=/box_data/ivb/nda/
# com.ibk.api.upload.tmp.path=/box_data/ivb/tmp/

# Content Path
com.ibk.content.img.path.ivt-v1=https://devinvest.ibkbox.net/api/iv/v1/file/render/image/
com.ibk.content.img.path.mnb-v1=https://devwww.ibkbox.net/renderImg.do?fileMngmNo=

# IBK \uD22C\uC790\uC0AC \uC0AC\uC5C5\uC790\uBC88\uD638 (\uC911\uC18C\uAE30\uC5C5\uC740\uD589)
# \uC5EC\uB7EC\uAC1C\uC77C \uACBD\uC6B0 \uAD6C\uBD84\uC790\uB85C , \uC0AC\uC6A9
ivt.ibk.vc.biznum = 2028100978

# \uD22C\uC790\uBC15\uC2A4 \uD504\uB860\uD2B8 \uB3C4\uBA54\uC778 \uACBD\uB85C (\uC54C\uB9BC URL)
ivt.alarm.page.host.url = https://devinvest.ibkbox.net

# \uC54C\uB9BC \uC911\uBD84\uB958 (\uD22C\uC790\uBC15\uC2A4)
adp.alarm.mddv.ivt.code = APP00046

# Alarm ID (\uC6B4\uC601\uC790\uD3EC\uD0C8 \uC54C\uB9BC\uC124\uC815)
adp.alarm.audit-suggest.id = A00080
adp.alarm.audit-request.id = A00081
adp.alarm.audit-change-step.id = A00082
adp.alarm.audit-over-time.id = A00083
adp.alarm.audit-message-receive.id = A00084
adp.alarm.consult-answer.id = A00085
adp.alarm.biz-inquiry.id = A00086
adp.alarm.biz-inquiry-answer.id = A00087
adp.alarm.qna-answer.id = A00088
adp.alarm.nda-request.id = A00089
adp.alarm.nda-change-step.id = A00090
adp.alarm.convert-investor.id= A00106
adp.alarm.convert-company.id= A00107

# Terms Number
adp.terms.personal-info.id = 10027
adp.terms.box-service.id = 10151

adp.terms.auto-scp-collect.id = 10146
adp.terms.auto-scp-trade-view.id = 10147
adp.terms.auto-scp-collect-choice.id = 10148

# stage profile swagger-ui turn off
springfox.documentation.enabled=false

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false